//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTTabBarLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QTTabBarLib.Resources_String", typeof(Resources_String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator;Go back;Go forward;Groups;Recently Closed;Applications;New window;Clone this;Lock;Copy Tool;TopMost;Close;Close all but current;Close window;Close left;Close right;Up one level;Reload;Search;Opacity;Search Box.
        /// </summary>
        public static string ButtonBar_BtnName {
            get {
                return ResourceManager.GetString("ButtonBar_BtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path;Name;Current folder path;Current folder name;MD5; items;Paths of all open tabs.
        /// </summary>
        public static string ButtonBar_Misc {
            get {
                return ResourceManager.GetString("ButtonBar_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List;Details;Tiles;Default.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK;Cancel;&amp;Apply;&amp;Default;Reset &amp;Page;&amp;Reset All;Reset;Add;Add...;Remove;Options;Enable;Disable;Undo;Load...;Save....
        /// </summary>
        public static string DialogButtons {
            get {
                return ResourceManager.GetString("DialogButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to:;Move to:;Create shortcut in:.
        /// </summary>
        public static string DragDropToolTip {
            get {
                return ResourceManager.GetString("DragDropToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.\r\nPlease make sure the file or the target of link exists:\r\n\r\n{0};Error - QTTabBar;Warning:  Could not automatically enable QTTabBar. To enable it manually, press and release the Alt key, then select QTTabBar from the View/Toolbars menu.;Could not enable;Error;Unable to load QTTabBar hook library.;Unable to initialize QTTabBar hook library.;Some features might not be functional. To resolve this, you may need to reinstall the application.;Failed to hook Desktop. Please re-enable QT Tab  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ErrorDialogs {
            get {
                return ResourceManager.GetString("ErrorDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files;Language Files;Plugin Files.
        /// </summary>
        public static string FileFilters {
            get {
                return ResourceManager.GetString("FileFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path;Hash;Close;Clear;Refresh;Always on top;Show result;Clear on close;Full path;(Now calculating...).
        /// </summary>
        public static string FileHashComputer {
            get {
                return ResourceManager.GetString("FileHashComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All;Left;Top;Right;Bottom.
        /// </summary>
        public static string MarginDropDown {
            get {
                return ResourceManager.GetString("MarginDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Search;Image file is invalid.\r\n\r\nPlease specify 432 x 40 px image file.;Search Results in;shortcut;Choose your file;Choose your folder;Experimental;dummy.
        /// </summary>
        public static string Misc_Strings {
            get {
                return ResourceManager.GetString("Misc_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change how Explorer Windows behave.;Single Window mode;Capture new Explorer windows as new tabs;Do not capture new Explorer windows;Default location for new windows and tabs;Session saving;Start a new session each time;Restore all tabs from the previous session;Restore only the locked tabs from the previous session;When the close button is clicked;Close the window;Close the current tab;Close all unlocked tabs;Send the window to the Task Tray on;Close;Minimize.
        /// </summary>
        public static string Options_Page01_Window {
            get {
                return ResourceManager.GetString("Options_Page01_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change options related to tabs.;Open new tabs:;When the current tab is closed, switch to the:;Switch to new tabs immediately;Reuse existing tabs;Rename ambiguous tabs;When drag-hovering over a tab,;Switch to it;Show the Subfolder Tip menu;Tab icons;Show folder icons on tabs;Show the Subfolder Tip menu when the icon is clicked;Show the drive letter on the icon;Close button;Show close button on tabs;Only with the Alt key down;Only on mouse hover;Tab Bar;Show navigation buttons on the tab bar;On the left;On th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Options_Page02_Tabs {
            get {
                return ResourceManager.GetString("Options_Page02_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable tweaks to Explorer&apos;s List View.;Tweaks that can be used with either List View;Display column headers in all view modes (Windows Vista/7);Use the standard filesystem view for Library folders (Windows 7);Deselect file extension when renaming files (Windows XP);Cycle selection with F2 while renaming;Wrap around when moving the selection with the arrow keys;Backspace goes up one level (Windows Vista/7);Scrolling with mouse wheel while holding shift scrolls horizontally;Tweaks that can only be  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Options_Page03_Tweaks {
            get {
                return ResourceManager.GetString("Options_Page03_Tweaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the behavior of Subfolder and Preview tooltips.;Subfolder Tips;Enable Subfolder Tips;Only with the Shift key is down;Show files;Show preview tooltips when mousing over menu items;Preview tooltips;Enable preview tooltips;Only with the Shift key is down;Show file information below images;Maximum Width x Height:;Font:;Text filetypes;Image and Video filetypes.
        /// </summary>
        public static string Options_Page04_Tooltips {
            get {
                return ResourceManager.GetString("Options_Page04_Tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General options for QTTabBar&apos;s behavoir.;Taskbar integration;Show tab previews on the Taskbar;History;Keep history of closed tabs;Clear now;Keep history of opened files;Network;Network timeout (Enter 0 for system default):;Check for updates periodically;Check now;Export;Export Settings...;Clear file history?;Clear tab history?.
        /// </summary>
        public static string Options_Page05_General {
            get {
                return ResourceManager.GetString("Options_Page05_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the appearance of tabs or the tab bar.;Tab image;Use custom tab image:;Sizing margins:;Overlap area:;Content margins:;Hit test transparent areas;Tab size;Height:;Min Width:;Max Width:;Sizing mode:;Full width;Same size;Tab text;Text Colors:;Shadow Colors:;Active Color;Inactive Color;Mouseover Color;Text Font:;Alignment:;Left;Center;Toolbar Background;Image;Solid color;Image each bar separately;Stretch mode:;Sizing margins:;Skin file;Import Skin...;Export Skin...;Stretch;True size;Tile.
        /// </summary>
        public static string Options_Page06_Appearance {
            get {
                return ResourceManager.GetString("Options_Page06_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign commands to different mouse actions.;To add a mouse binding, perform a mouse action on the plus icon to the left of the appropriate target type.  To remove a binding, select it in the list and press the Delete key.;Other mouse options;Mouse wheel scrolls the window under the mouse;Mouse Chord;Action;Anywhere;Tab;Tab Bar Background;Folder Link;File or Folder;Explorer Background;Left Click;Right Click;Middle Click;Double Click;X1 Click;X2 Click;This mouse button cannot be used for this target.;The vali [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Options_Page07_Mouse {
            get {
                return ResourceManager.GetString("Options_Page07_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change keyboard shortcuts.;Select an action from the list and press the key gesture you would like to bind to it.  Press Escape to clear the binding.;Other keyboard options;Show the Tab Switcher window when Ctrl + Tab is pressed;Action;Keystroke;This key is already assigned to:;Should it be reassigned?;Keystroke conflict.
        /// </summary>
        public static string Options_Page08_Keys {
            get {
                return ResourceManager.GetString("Options_Page08_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and manage tab groups.;To assign a Shortcut Key to a group, select it and press the appropriate key gesture.  Press Escape to clear the binding.;Create New Group;Folder;Startup;Shortcut Key;New Group;Open group &quot;{0}&quot;.
        /// </summary>
        public static string Options_Page09_Groups {
            get {
                return ResourceManager.GetString("Options_Page09_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcuts to commonly used files or applications.;To assign a Shortcut Key to an application, select it and press the appropriate key gesture.  Press Escape to clear the binding.;Create New Folder;Path:;Arguments:;Working Directory:;Application;Shortcut Key;The following keywords are replaced with double-quoted path strings at runtime.;Selected files.;Selected folders.;Selected files and folders.;Current folder.;Current folder if no selection, otherwise selected folder.;New Folder;Remove this folder  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Options_Page10_Apps {
            get {
                return ResourceManager.GetString("Options_Page10_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the Button Bar.;Buttons;Button Bar Options;Large icons;Show labels on buttons;Lock the order of dropdown button menus;Lock the size of the search box;Custom Button Images.
        /// </summary>
        public static string Options_Page11_ButtonBar {
            get {
                return ResourceManager.GetString("Options_Page11_ButtonBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage third-party plugins.;Install a Plugin;(Disabled);by {0};{0} has been removed.;This plugin will be installed when you press OK or Apply.;This plugin will be enabled when you press OK or Apply.;This plugin will be disabled when you press OK or Apply.;Uninstalling this plugin will also uninstall the following plugins:;Proceed?.
        /// </summary>
        public static string Options_Page12_Plugins {
            get {
                return ResourceManager.GetString("Options_Page12_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the language.;Main language;Use built-in language:;Use language file:;Plugin language files;Language File Editor;Show Language Editor...;Original;Translated;Reset all entries to their original value?;Error saving file..
        /// </summary>
        public static string Options_Page13_Language {
            get {
                return ResourceManager.GetString("Options_Page13_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View credits and version information.;Original code by {0};Lead Developer:;Other Developers:;Icons and graphics:;If you find QTTabBar useful, please consider making a small donation..
        /// </summary>
        public static string Options_Page14_About {
            get {
                return ResourceManager.GetString("Options_Page14_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTTabBar Options;Reset all options on this page to their default values?;Reset all options to their default values?  This will not affect Groups, Applications, or Plugins.;Confirmation.
        /// </summary>
        public static string OptionsDialog {
            get {
                return ResourceManager.GetString("OptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/donate/index.php?group_id=312930.
        /// </summary>
        public static string PayPalURL {
            get {
                return ResourceManager.GetString("PayPalURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back;Go forward;Go back to start;Go forward to end;Select next tab;Select previous tab;Select first tab;Select last tab;Switch to last activated tab;Open new tab;Open new window;Merge tabs from other windows;Close current tab;Close all but current;Close left;Close right;Close window;Undo close;Clone current tab;Open current folder in new window;Lock / unlock current;Lock / unlock all;Browse folder;Create new group;Open option dialog;Show toolbar menu;Show current tab menu;Show group menu (Button Bar);Sho [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ShortcutKeys_ActionNames {
            get {
                return ResourceManager.GetString("ShortcutKeys_ActionNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTTabBar;{0} (Plugin).
        /// </summary>
        public static string ShortcutKeys_Groups {
            get {
                return ResourceManager.GetString("ShortcutKeys_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.qttabbar.sf.net.
        /// </summary>
        public static string SiteURL {
            get {
                return ResourceManager.GetString("SiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close;Close right;Close left;Close all but this;Add to Group;Create new Group;Lock;Clone this;New window;Copy path;Properties;Tab history;Groups;Undo closed;Last activated;Recently opened files;Browse folder;Close all but current;Close Window;Options;Unlock;Add to Application menu : ;items;Cancel;Branches;Remove this item from menu;O&amp;pen containing folder;Tab label;Tab order;Name;Path;Active;Lock the Toolbars;Merge tabs of other windows;Invert.
        /// </summary>
        public static string TabBar_Menu {
            get {
                return ResourceManager.GetString("TabBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTTabBar failed to open
        ///
        /// &quot;{0}&quot;..
        /// </summary>
        public static string TabBar_Message {
            get {
                return ResourceManager.GetString("TabBar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Group;Group name:;Add all tabs.
        /// </summary>
        public static string TabBar_NewGroup {
            get {
                return ResourceManager.GetString("TabBar_NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window;Tabs;Tweaks;Tooltips;General;Appearance;Mouse;Keys;Groups;Applications;Button Bar;Plugins;Language;About.
        /// </summary>
        public static string TabBar_Option_Genre {
            get {
                return ResourceManager.GetString("TabBar_Option_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar;Desktop;Lock items;Draw title background;Menu by one click;Enable application shortcut keys.
        /// </summary>
        public static string TaskBar_Menu {
            get {
                return ResourceManager.GetString("TaskBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups;Undo closed;Applications;Recently opened files.
        /// </summary>
        public static string TaskBar_Titles {
            get {
                return ResourceManager.GetString("TaskBar_Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 window;{0} windows.
        /// </summary>
        public static string TrayIcon {
            get {
                return ResourceManager.GetString("TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of QTTabBar has been released:;Press OK to go to the web site.;Your version of QTTabBar is up to date.;New development version found:;Version file not found (404).;Unknown network error.;Server not found.;Server returned wrong strings..
        /// </summary>
        public static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
    }
}
